### ISSUE TITLE
Specify which version of FTXUI to use.

### ISSUE THREAD

**Issue by ArthurSonzogni** [SAtacker/beagle-config#1]
To avoid being broken by non backward compatible change from FTXUI, its version can be specified:
```cmake
FetchContent_Declare(ftxui
  GIT_REPOSITORY https://github.com/ArthurSonzogni/ftxui
  GIT_TAG 87a1d75bf1c1ee964e8eed4a6686544ae3b44116
)
```

FTXUI merge the `mouse support` and `functional component`, which broke beagle-config.

**Comment by SAtacker** [comment]
Yes, Thank you for providing the GIT_TAG.

**Comment by ArthurSonzogni** [comment]
I tried to make the ftxui/component part more functional.
The example become:
https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/slider_rgb.cpp

**Comment by SAtacker** [comment]
I think I should close this issue now.
